import { type ClassValue, clsx } from 'clsx';
import e from 'express';
import { Metadata } from 'next';
import { twMerge } from 'tailwind-merge';

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

export function formatPrice(
  price: number | string,
  options: {
    currency?: 'USD' | 'EUR' | 'GBP' | 'BDT';
    notation?: Intl.NumberFormatOptions['notation'];
  } = {},
) {
  const { currency = 'USD', notation = 'compact' } = options;

  const numericPrice = typeof price === 'string' ? parseFloat(price) : price;

  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency,
    notation,
    maximumFractionDigits: 2,
  }).format(numericPrice);
}

export function constructMetadata({
  title = 'Yehfedra - The go to for verified digital goods.',
  description = ' Yehfedra is an open-source marketplace The go to for verified digital goods.',
  image = '/thumbnail.png',
  icons = '/public/favicon.ico',
  noIndex = false,
}: {
  title?: string;
  description?: string;
  image?: string;
  icons?: string;
  noIndex?: boolean;
} = {}): Metadata {
  return {
    title,
    description,
    openGraph: {
      title,
      description,
      images: [
        {
          url: image,
        },
      ],
    },
    twitter: {},
    keywords: [
      'STEVEN',
      'GARIBALDI',
      'STEVEN GARIBALDI',
      'Steven Garibaldi',
      'steven garibaldi',
      'Steven garibaldi',
      'garibaldi',
      'yehfedra',
      'Yehfedra',
      'YEHFEDRA',
      'yehfedra.com',
      'Yehfedra.com',
      'Yehfedrah.com',
      'Yehfedrah',
      'YEHFEDRAH',
      'YEHFEDRAH.com',
      'YEHFEDRAH',
      'yehfedrah',
      'yehfedrah',
      'YEHFEDRA.com',
      'yehfedra marketplace',
      'Yehfedra marketplace',
      'YEHFEDRA marketplace',
      'yehfedra digital goods',
      'Yehfedra digital goods',
      'YEHFEDRA digital goods',
      'yehfedra digital assets',
      'Yehfedra digital assets',
      'YEHFEDRA digital assets',
      'yehfedra digital marketplace',
      'Yehfedra digital marketplace',
      'YEHFEDRA digital marketplace',
      'yehfedra store',
      'Yehfedra digital ',
      'YEHFEDRA digital assets',
      'y3hfedra',
      'yahfedra',
      'yihfedra',
      'yebfedra',
      'yenfedra',
      'yehdedra',
      'yehgedra',
      'yehvedra',
      'yehf3dra',
      'yehfadra',
      'yehfidra',
      'yehfesra',
      'yehfefra',
      'yehfedta',
      'yehfedea',
      'yehfedrs',
      'yehfedrq',
      'ehfedra',
      'yhfedra',
      'yefedra',
      'yehedra',
      'yehfdra',
      'yehfera',
      'yehfeda',
      'yehfedr',
      'ayehfedra',
      'eyehfedra',
      'iyehfedra',
      'oyehfedra',
      'uyehfedra',
      'yaehfedra',
      'yeehfedra',
      'yiehfedra',
      'yoehfedra',
      'yuehfedra',
      'yeahfedra',
      'yeehfedra',
      'yeihfedra',
      'yeohfedra',
      'yeuhfedra',
      'yehafedra',
      'yehefedra',
      'yehifedra',
      'yehofedra',
      'yehufedra',
      'yehfaedra',
      'yehfeedra',
      'yehfiedra',
      'yehfoedra',
      'yehfuedra',
      'yehfeadra',
      'yehfeedra',
      'yehfeidra',
      'yehfeodra',
      'yehfeudra',
      'yehfedara',
      'yehfedera',
      'yehfedira',
      'yehfedora',
      'yehfedura',
      'yehfedraa',
      'yehfedrea',
      'yehfedria',
      'yehfedroa',
      'yehfedrua',
      'yehfedraa',
      'yehfedrae',
      'yehfedrai',
      'yehfedrao',
      'yehfedrau',
      'eyhfedra',
      'yhefedra',
      'yefhedra',
      'yehefdra',
      'yehfdera',
      'yehferda',
      'yehfedar',
      'digital goods',
      'digital',
      'goods',
      'digital goods marketplace',
      'digital marketplace',
      'digital goods store',
      'digital store',
      'digital goods shop',
      'digital shop',
      'digital assets',
      'digital asset',
      'digital asset marketplace',
      'digital asset store',
      'digital asset shop',
      'full stack developer',
      'full stack',
      'developer',
      'web developer',
      'y3hfedra',
      'yahfedra',
      'yihfedra',
      'yebfedra',
      'yenfedra',
      'yehdedra',
      'yehgedra',
      'yehvedra',
      'yehf3dra',
      'yehfadra',
      'yehfidra',
      'yehfesra',
      'yehfefra',
      'yehfedta',
      'yehfedea',
      'yehfedrs',
      'yehfedrq',
      'ehfedra',
      'yhfedra',
      'yefedra',
      'yehedra',
      'yehfdra',
      'yehfera',
      'yehfeda',
      'yehfedr',
      'ayehfedrah',
      'eyehfedrah',
      'iyehfedrah',
      'oyehfedrah',
      'uyehfedrah',
      'yaehfedrah',
      'yeehfedrah',
      'yiehfedrah',
      'yoehfedrah',
      'yuehfedrah',
      'yeahfedrah',
      'yeehfedrah',
      'yeihfedrah',
      'yeohfedrah',
      'yeuhfedrah',
      'yehafedrah',
      'yehefedrah',
      'yehifedrah',
      'yehofedrah',
      'yehufedrah',
      'yehfaedrah',
      'yehfeedrah',
      'yehfiedrah',
      'yehfoedrah',
      'yehfuedrah',
      'yehfeadrah',
      'yehfeedrah',
      'yehfeidrah',
      'yehfeodrah',
      'yehfeudrah',
      'yehfedarah',
      'yehfederah',
      'yehfedirah',
      'yehfedorah',
      'yehfedurah',
      'yehfedraah',
      'yehfedreah',
      'yehfedriah',
      'yehfedroah',
      'yehfedruah',
      'yehfedraah',
      'yehfedraeh',
      'yehfedraih',
      'yehfedraoh',
      'yehfedrauh',
      'eyhfedrah',
      'yhefedrah',
      'yefhedrah',
      'yehefdrah',
      'yehfderah',
      'yehferdah',
      'yeh fedra',
      'yeh fed rah',
      'YEH FED RAH',
      'YEH FEDRAH',
      'YEH FEDRAH.com',
      'YEH FEDRAH',
      'YEH FED',
      'YFEDRA',
    ],

    icons,
    // metadataBase: new URL('https://localhost:3000'),
    metadataBase: new URL('https://www.yehfedra.com'),

    ...(noIndex && {
      robots: {
        index: false,
        follow: false,
      },
    }),
  };
}
